### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [bobrk/h-beam-piper_murder-in-the-gunroom#1]
### Modernize hyphenation and spelling

- [x] Incorrect "any way -> anyway" change in [chapter 10](https://github.com/bobrk/h-beam-piper_murder-in-the-gunroom/blob/081d72dd45af01faa6b70dda559c68aa80a8b4d9/src/epub/text/chapter-10.xhtml#L116l) ("is there any way into the house")

### Semantication

- [x] I see that in some cases you have semanticated "S. North" as `<abbr epub:type="z3998:initialism">S.</abbr> North`. My research suggests that the "S" here should be an abbreviation for "Simeon" ([source](https://americanhistory.si.edu/collections/search/object/nmah_438546)). I think `z3998:given-name` would be a more appropriate semantic.
- [x] "seppuku" is italicized but in M-W: https://www.merriam-webster.com/dictionary/seppuku
- [x] "HNO3" in chapter 17 should follow the [chemicals and compounds rules](https://standardebooks.org/manual/1.6.2/8-typography#8.12)
- [x] Chapter 10 has a bare italic `<i>Gewehr ’98</i>` which I think should be marked as German
- [x] Chapter 10, in `<i>J</i>-sound as though it were <i>Zh</i>`, the sounds should be semanticated as phonemes (see [8.2.8.4](https://standardebooks.org/manual/1.6.2/8-typography#8.2.8.4))
- [x] Chapter 21 has an editorial title italicized as `<i>Trial by Pistol</i>`, but that should be in quotation marks instead since [newspaper articles are not italicized](https://standardebooks.org/manual/1.6.2/8-typography#8.2.11.3).
- [x] Chapter 5 has `<i>Sons of the hound, come and get flesh!</i>` which seems like it should be emphasized in context, so `<em>` and not `<i>`
- [x] [This commit](https://github.com/bobrk/h-beam-piper_murder-in-the-gunroom/commit/1d7ea66ec16e63832ed70108045eed4e702bd68a) looks like an editorial change from the original formatting. I see [8.3.3](https://standardebooks.org/manual/1.6.2/8-typography#8.3.3) does include the example of a sign as a time when `<b>` is used but I think that's for the case when the book already has small caps. In this case I think you should stick to the original (unsemantic) formatting of the book, so you should revert this change. (If you feel really comfortable with Git, you might consider dropping this commit completely using [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).) Same thing with the `<i>` to `<b>` changes in [this commit](https://github.com/bobrk/h-beam-piper_murder-in-the-gunroom/commit/5e61ddc59b918acce0d550e71e0adb5870028911). 
- [x] The card in chapter 10 seems to have some unsemanticated abbreviations: `O.A.` `abt` `Mo.` I am not sure what `RLss`, `NLss` etc. mean but they also look like abbreviations of some sort.

### Typography

- [x] I see that in [this commit](https://github.com/bobrk/h-beam-piper_murder-in-the-gunroom/commit/61a6e1adcd1ad0d76b411b7df347faf20da70d9b) you changed the four periods in a row `....` to the horizontal ellipse `…` with the preceding spacing characters. If you run `typogrify` on the four periods in a row, it should give you `.[spacing characters]…`, which should be the correct typography. It looks like you might have deleted the first period, which is necessary since that's the period that indicates the end of the sentence before the pause indicated by the ellipse.
- [x] I see you changed "AP" to "A.P." for what I assume is the Associated Press, which I think technically follows the rules of the manual, but I am not sure if that is correct. I think the correct way to style "AP" both now and when this book was written is without periods. We can raise this with Alex since I think this should be one of the exceptions.

### Dedication

- [x] "W." in "Henry W. Shoemaker" needs abbreviation semantics
- [x] Rather than the weird "T O" formatting (which I think will screw with screen readers), I think it would be better to use `<b>` without the space, i.e. `<b>To</b>`.
- [x] One thing you can do to make the dedication look a little bit more like the printed version is use CSS to add margins to separate the paragraphs.

### Metadata

- [x] Book should have "Fiction" subject

**Comment by bobrk** [comment]
On Wehrmacht and seppuku I was following the advice on the list that if it wasn't in the abridged dictionary then it should be italicized. You'll note that the dictionary definitions both feature the "Free trial" banner for the unabridged dictionary, and I was instructed that that wasn't a valid dictionary entry. It seems like there is some dissension about this, and I'll go with whichever is decided. https://groups.google.com/g/standardebooks/c/91ZcfmF3uMc/m/ZPslRJZ0AQAJ

**Comment by weijia-cheng** [comment]
Ok, looks like Wehrmacht is an unabridged word, though looking at seppuku I don't see the banner so I think "seppuku" is in the normal version of the dictionary.

**Comment by bobrk** [comment]
for the "J-sound to Zh" fix, the J is not a phoneme, correct, just the Zh?

**Comment by bobrk** [comment]
I found another abbreviation, which is "Mo.", like Missouri, I think. Is this to be converted to MO or left as is? I will add the "place" semantication either way.

**Comment by weijia-cheng** [comment]
> for the "J-sound to Zh" fix, the J is not a phoneme, correct, just the Zh?

No, I think both are phonemes here.

> I found another abbreviation, which is "Mo.", like Missouri, I think. Is this to be converted to MO or left as is? I will add the "place" semantication either way.

We should follow [8.10.6](https://standardebooks.org/manual/1.6.2/8-typography#8.10.6) for any state abbreviations.

Also, it looks like [Alex agrees that we should stick with AP for "Associated Press."](https://groups.google.com/g/standardebooks/c/91ZcfmF3uMc/m/xGQWFUf2BwAJ)

**Comment by weijia-cheng** [comment]
Also, I think you missed a "S. North":

```
src/epub/text/chapter-7.xhtml:                  <p>There was no Hall breechloader, either, but there was a dilapidated old Ketland. There were many such interlopers among the <abbr epub:type="z3998:initialism">U.S.</abbr> Martials: an English ounce-ball cavalry pistol, a French 1777 and a French 1773, a couple more $6.95 bargain-counter specials, a miserable altered <abbr epub:type="z3998:initialism">S.</abbr> North 1816. Among the Colts, there was some awful junk, including a big Spanish hinge-frame .44 and a Belgian imitation of a Webley <abbr epub:type="z3998:initialism">R.I.C.</abbr> Model. There weren’t as many Paterson Colts as Gresham had spoken of, and the Whitneyville Walker was absent. It went on like that; about a dozen of the best pistols which Rand remembered having seen from two years ago were gone, and he spotted at least twenty items which the late Lane Fleming wouldn’t have hung in his backyard privy, if he’d had one.</p>
```

**Comment by bobrk** [comment]
Just wanted to let you know I'm close to finishing up. I've fixed all the issues but the metadata. 

I'm still working on your idea for using css to style the dedication. One issue is that I can't figure out what the boilerplate dedication formatting is doing. I'm finding myself making changes there and then building the book to see what the differences are; sometimes I get lucky, most often I don't. The "Section" selector overrides are interesting, it looks like there is some kind of search going on to see if this needs to be applied to dedication files. Also, should I just use divs instead of forcing things to fit into paragraphs? Perhaps:

<div>To</div>
<div><I>name</I></div>
<p>paragraph of some justified text</p>

Any tips there would be appreciated.

**Comment by weijia-cheng** [comment]
I felt like playing around with the styling a bit so I put together a PR for the dedication: https://github.com/bobrk/h-beam-piper_murder-in-the-gunroom/pull/2

I think the best way to style the dedication is as a single `<p>` with breaks (`<br/>`s) because it is a single paragraph. So, I styled individual breaks with `line-height` to create the spacing effect the original printing has.

**Comment by weijia-cheng** [comment]
Ok, it looks like lint turns up a few more things. The first is that the `se:subject`s are not in alphabetical order. The second a warning that the "Colonel Henry W. Shoemaker" line has `text-align: center` but the `text-indent` is `1em`. To fix that you will have to add a `text-indent: 0;` line to the `#dedication p:nth-of-type(2)` selector. I also noticed that the "W." in "Henry W. Shoemaker" still needs an abbreviation tag. Once that's done I think this should be ready to pass on to Alex.

**Comment by bobrk** [comment]
Yeah, and it also looks like I didn’t get all the sign semantication fixed.

**Comment by bobrk** [comment]
Ok, I’m done with it. Thanks for your help!

Bob

**Comment by weijia-cheng** [comment]
Ok, you just need to run `se clean .` one more time because we have an extra space in local.css for some reason.

**Comment by bobrk** [comment]
Bad cut-n-paste. fixed.

Bob
